/** @type {import("stylelint").Config} */
export default {
  plugins: [
    'stylelint-order',
    'stylelint-scss',
    'stylelint-selector-bem-pattern',
  ],
  extends: ['stylelint-config-standard-scss'],
  defaultSeverity: 'warning',
  ignoreFiles: ['**/*.css'],
  rules: {
    // 'comment-empty-line-before': null,
    'block-no-redundant-nested-style-rules': null,
    'custom-property-empty-line-before': null,
    'property-no-vendor-prefix': null,
    'selector-not-notation': null,
    'declaration-empty-line-before': null,
    'block-no-empty': null,
    'selector-class-pattern': null,
    'scss/at-rule-conditional-no-parentheses': null,
    'plugin/selector-bem-pattern': {
      componentName: '[A-Z]+',
      componentSelectors: {
        initial: '^\\.{componentName}(?:-[a-z]+)?$',
        combined: '^\\.combined-{componentName}-[a-z]+$',
      },
      utilitySelectors: '^\\.util-[a-z]+$',
    },
    'declaration-no-important': [
      true,
      {
        severity: 'warning', // или 'error'
      },
    ],
    // порядок свойств
    'order/properties-order': [
      [
        'box-sizing',
        'content',
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'inset',
        'inset-block-start',
        'inset-inline-end',
        'inset-block-end',
        'inset-inline-start',
        'z-index',
        'grid-area',
        'box-sizing',
        'display',
        'float',
        'width',
        'max-width',
        'min-width',
        'height',
        'max-height',
        'min-height',
        'inline-size',
        'min-inline-size',
        'max-inline-size',
        'block-size',
        'min-block-size',
        'max-block-size',
        'grid-template-columns',
        'grid-template-rows',
        'grid-template-areas',
        'flex-direction',
        'justify-content',
        'justify-self',
        'align-items',
        'align-self',
        'align-content',
        'gap',
        'row-gap',
        'column-gap',
        'flex',
        'flex-shrink',
        'flex-grow',
        'flex-basis',
        'order',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'margin-inline',
        'margin-inline-start',
        'margin-inline-end',
        'margin-block',
        'margin-block-start',
        'margin-block-end',
        'padding-inline',
        'padding-inline-start',
        'padding-inline-end',
        'padding-block',
        'padding-block-start',
        'padding-block-end',
        'border',
        'border-width',
        'font',
        'font-family',
        'font-style',
        'font-size',
        'font-weight',
        'line-height',
        'color',
        'text-transform',
        'background',
        'border-radius',
        'text-shadow',
        'opacity',
        'transition',
        'transition-property',
        'transition-duration',
        'transition-timing-function',
        'transition-delay',
        'transform',
        'text-align',
        'will-change',
      ],
      {
        unspecified: 'bottomAlphabetical',
      },
    ],

    'order/order': [
      'custom-properties',
      'dollar-variables',
      'declarations',
      // { type: 'at-rule', name: 'include' },
      { type: 'at-rule', name: 'media' },

      // простые псевдоклассы самого блока: .test:hover
      { type: 'rule', selector: '^&:[a-zA-Z-]+$' },

      // простые модификаторы: .test--blue
      { type: 'rule', selector: '^&--[a-zA-Z0-9-]+$' },

      // псевдоэлементы самого блока: .test::before
      { type: 'rule', selector: '^&::(before|after)$' },

      // элементы: .test__child
      // { type: 'rule', selector: '^&__' },
    ],
  },
}
